# -*- mode: ruby -*-
# vi:set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  provisioner = Vagrant::Util::Platform.windows? ? :guest_ansible : :ansible

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 16384
	vb.cpus = 4
	vb.gui = false
  end

  config.vm.define "centos7" do |docker|
    docker.vm.network :private_network, ip: "192.168.56.10"
    docker.vm.hostname = "centos7-server"
    docker.vm.provision provisioner do |ansible|
    ansible.playbook = "../provisioning/playbook.yml"
    ansible.tags="centos"
    end
  end
end
