# -*- mode: ruby -*-
# vi:set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  provisioner = Vagrant::Util::Platform.windows? ? :guest_ansible : :ansible

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
	vb.cpus = 4
	#vb.gui = false
    #vb.customize ["modifyvm", :id, "--nictype1", "virtio"]        
  end

  config.vm.define "centos7" do |centos|
    #centos.vm.network :private_network, ip: "192.168.56.10"
    centos.vm.network :private_network, ip: "192.168.200.10"
    centos.vm.hostname = "centos7-server"
    centos.vm.provision provisioner do |ansible|
    #centos.vm.synced_folder '.', '/vagrant', disabled: true
    centos.vm.synced_folder '.', '/vagrant', type: "rsync"
    #centos.vm.synced_folder ".", "/vagrant", :nfs => { :mount_options => ["dmode=777","fmode=777"] }
    centos.vm.boot_timeout
    ansible.playbook = "../provisioning/playbook.yml"
    ansible.tags="centos"
    end
  end
end
