---
- hosts: centos8,centos7
  become: true
  roles:
  - role: common
  tags:
  - centos

- hosts: ubuntu20
  become: true
  roles:
  - role: common
  tags:
  - ubuntu

- hosts: all
  gather_facts: false
  become: true
  roles:
  - role: docker
  tags:
  - docker
