---
- hosts: centos7,centos8,rocky8
  become: true
  #gather_facts: false
  roles:
  - role: common
  tags:
  - centos
  - rocky

- hosts: ubuntu20
  become: true
  #gather_facts: false
  roles:
  - role: common
  tags:
  - ubuntu

- hosts: opensuse15
  become: true
  roles:
  - role: common
  tags:
  - opensuse

- hosts: all
  gather_facts: false
  become: true
  roles:
  - role: docker
  tags:
  - docker
