# -*- mode: ruby -*-
# vi:set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Leap-15.2.x86_64"
  provisioner = Vagrant::Util::Platform.windows? ? :guest_ansible : :ansible

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
	vb.cpus = 4
	#vb.gui = false
  end

  config.vm.define "opensuse15" do |opensuse|
    opensuse.vm.network :private_network, ip: "192.168.56.30"
    opensuse.vm.hostname = "opensuse15-server"
    opensuse.vm.provision provisioner do |ansible|
    opensuse.vm.synced_folder '.', '/vagrant', disabled: true
    ansible.playbook = "../provisioning/playbook.yml"
    ansible.tags="opensuse"
    end
  end
end
