---
- name: install default packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - "wget"
    - "vim"
    - "net-tools"
    - "epel-release"
    - "chrony"

- name: disable selinux
  selinux:
    state: disabled

- name: disable NetworkManager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no

# can login with vagrant(ID)/vagrant(password) 
- name: setup the sshd config for connecting with password
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication no"
    line: "PasswordAuthentication yes"

- name: setup the sshd config for connecting as root permission
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#PermitRootLogin yes"
    line: "PermitRootLogin yes"

- name: restart sshd service
  systemd:
    name: sshd
    state: restarted

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
